# SITE CONFIGURATION
baseurl: ""
url: "https://www.jadin.me"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Taylor Jadin
  avatar: assets/img/caricature.jpg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: > #two or three lines to describe your site
    <p>Hi! I'm Taylor.</p>
    <p>This is the home for stuff I put on the internet.</p>
    <p>I <a href="https://twitter.com/taylorjadin">tweet</a>, post pictures to <a href="https://www.instagram.com/taylor_jadin/">Instagram</a>, and occasionally <a href="https://github.com/taylorjadin">write code</a>. I also say words on the <a href="https://magecast.net">Edtech Magecast</a>, and the <a href="https://soundcloud.com/jadinapproved>Jadin Approved podcast</a>.
  header_text_feature_image: 
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: true
  email_address:
  behance:
  bitbucket:
  dribbble:
  facebook: taylorjadin
  flickr:
  gitlab:
  github: taylorjadin
  google_plus:
  instagram: taylor_jadin
  keybase:
  linkedin: https://www.linkedin.com/in/taylor-jadin-78a51482/
  pinterest:
  reddit:
  soundcloud: jadinapproved
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: taylorjadin
  vimeo:
  wordpress:
  youtube: UCDFYVLncztnWlIDyPYLUbGg

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  portfolio: false
  search: true
  tags: true
  
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
theme: type-on-strap # If using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
